name: Intent Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: intentArchitectVersion
    attributes:
      label: What version of Intent Architect are you using?
      options:
        - 3.4.3
        - 3.4.4
        - 4.0.0-beta.4
        - 4.0.0-beta.5
    validations:
      required: true
  - type: dropdown
    id: intentArchitectModule
    attributes:
      label: Is this problem specific to a module?
      options:
        - My own module- Intent.Application.AutoMapper
        - Intent.Application.DependencyInjection
        - Intent.Application.DependencyInjection.AutoMapper
        - Intent.Application.DependencyInjection.FluentValidation
        - Intent.Application.DependencyInjection.MediatR
        - Intent.Application.Dtos
        - Intent.Application.Dtos.AutoMapper
        - Intent.Application.Dtos.Pagination
        - Intent.Application.FluentValidation
        - Intent.Application.Identity
        - Intent.Application.MediatR
        - Intent.Application.MediatR.Behaviours
        - Intent.Application.MediatR.CRUD
        - Intent.Application.MediatR.CRUD.Eventing
        - Intent.Application.MediatR.FluentValidation
        - Intent.AspNetCore
        - Intent.AspNetCore.Controllers
        - Intent.AspNetCore.Controllers.Dispatch.MediatR
        - Intent.AspNetCore.Docker
        - Intent.AspNetCore.Swashbuckle
        - Intent.AspNetCore.Swashbuckle.Security
        - Intent.Common
        - Intent.Common.CSharp
        - Intent.Common.Types
        - Intent.DomainEvents
        - Intent.DomainServices
        - Intent.Entities
        - Intent.Entities.Repositories.Api
        - Intent.EntityFrameworkCore
        - Intent.EntityFrameworkCore.Interop.DomainEvents
        - Intent.EntityFrameworkCore.Repositories
        - Intent.Eventing.Contracts
        - Intent.Eventing.Contracts.DomainMapping
        - Intent.Eventing.MassTransit
        - Intent.Eventing.MassTransit.EntityFrameworkCore
        - Intent.Infrastructure.DependencyInjection
        - Intent.MediatR.DomainEvents
        - Intent.Metadata.RDBMS
        - Intent.Metadata.WebApi
        - Intent.Modelers.Domain
        - Intent.Modelers.Domain.Events
        - Intent.Modelers.Domain.Services
        - Intent.Modelers.Domain.ValueObjects
        - Intent.Modelers.Eventing
        - Intent.Modelers.Services
        - Intent.Modelers.Services.CQRS
        - Intent.Modules.AspNetCore.Logging.Serilog
        - Intent.OutputManager.RoslynWeaver
        - Intent.Security.JWT
        - Intent.ValueObjects
        - Intent.VisualStudio.Projects
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
